### PR TITLE
Added: Original files from previous Vento-Rest_Services

### PR DESCRIPTION
**Pull request by IAMLEGION98**
This PR has been created to merge back the original files from the previous Vento/rest-services, which had the updated files.

### CODE REVIEW

**Comment by Jayalakshmi02** [comment]
Testing Permissions API
GET:
Screenshot (76)
Get By ID:
Screenshot (41)
Get by query:
Screenshot (78)
POST:
Screenshot (79)
MultiCreate:
Screenshot (80)
PUT:
Screenshot (81)
DELETE:
Screenshot (82)
MultiDelete:
Screenshot (83)

**Comment by Jayalakshmi02** [comment]
Testing Products API
GET:
Screenshot (84)
Get By ID:
Screenshot (85)
Get by query:
Screenshot (86)
POST:
Screenshot (87)
MultiCreate:
Screenshot (88)
PUT:
Screenshot (89)
DELETE:
Screenshot (90)
MultiDelete:
Screenshot (91)

**Comment by IAMLEGION98** [comment]
Tested Api's Functionality
### Asset Consumer Map
**GET and GET by ID**
Screen Shot 2020-04-14 at 12 36 52 PM
Screen Shot 2020-04-14 at 12 37 07 PM
**Multi Create**
Screen Shot 2020-04-14 at 12 36 26 PM

**MultiDelete
Screen Shot 2020-04-14 at 12 45 07 PM
**

**Update**
putacons

**Comment by IAMLEGION98** [comment]
Tested Asset Notification Map

1. GET and GET BY ID
Screen Shot 2020-04-14 at 12 46 04 PM

Screen Shot 2020-04-14 at 12 46 19 PM

2. Post 




3. Put
Screen Shot 2020-04-14 at 12 50 30 PM

4. Delete/ Multidelete

md

**Comment by Jayalakshmi02** [comment]
Testing Roles API:
GET:
Screenshot (98)
Get By ID:
Screenshot (93)
Get by query:
Screenshot (110)
POST:
Screenshot (96)
MultiCreate:
Screenshot (99)
PUT:
Screenshot (100)
DELETE:
Screenshot (101)
MultiDelete:
Screenshot (102)

**Comment by Jayalakshmi02** [comment]
Testing RolePermissionMap API
GET:
Screenshot (103)
Get By ID:
Screenshot (104)
POST:
Screenshot (105)
MultiCreate:
Screenshot (106)
PUT:
Screenshot (107)
DELETE:
Screenshot (108)
MultiDelete:
Screenshot (109)

**Comment by IAMLEGION98** [comment]
### Testing Departments API
**1. GET and GET BY ID**
Screen Shot 2020-04-14 at 12 51 51 PM
Screen Shot 2020-04-14 at 12 52 04 PM

**2. POST**
Screen Shot 2020-04-14 at 12 52 43 PM

**3. PUT/ UPDATE**
Screen Shot 2020-04-14 at 12 53 32 PM

**4. Delete/ MultiDelete**
Screen Shot 2020-04-14 at 12 56 26 PM

**Comment by IAMLEGION98** [comment]
### Testing Assets API

**1 GET and GET BY ID**
Screen Shot 2020-04-14 at 12 57 37 PM
Screen Shot 2020-04-14 at 12 58 13 PM

2. POST- Create an ASSET
Screen Shot 2020-04-14 at 12 58 42 PM

3. Update an Asset
Screen Shot 2020-04-14 at 12 59 32 PM

4. Delete/ MultiDelete an asset

**Comment by DhyaniKanika** [comment]
Testing User APIs
GET:
image
 GET by ID:
image
PUT: 
image
MULTICREATE:
image
DELETE:
image
MULTIDELETE;
image

**Comment by DhyaniKanika** [comment]
Testing Notifications APIs
GET:
image

GET by ID:
image

POST:
image

PUT:
image

MULTICREATE:
image

MULTIDELETE:
image

**Pull request merged**
